include:
  - path: "backend-services/compose.yaml"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - 3000:3000
    depends_on:
      - reverse-proxy
