name: repairs-backend

services:
  repairs:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3003:80
    env_file:
      - ../.env
      - ./.env
    networks:
      - repairs-net
      - blacklist-net
    depends_on:
      - repairs-postgres
      - repairs-redis
      - redis-blacklist
  repairs-postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=repairs
    volumes:
      - type: bind
        source: ./db_config/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - repairs-net
  repairs-redis:
    image: redis:alpine3.22
    networks:
      - repairs-net

networks:
  repairs-net:
